repository: delphix/delphix.github.io

featured:
  - name: "Tools"
    description: "Tools for managing Delphix deployments."
    repos: [ "dxtoolkit", "dxanalyze", "infra-readiness" ]
  - name: "Forks" 
    description: "Forks of external projects where Delphix is a primary contributor."
    repos: [ "delphix-os" ]
