repository: delphix/delphix.github.io
plugins_dir: ./_plugins

jekyll_get:
  - data: jenkins
    json: 'https://api.github.com/repos/jenkinsci/delphix-plugin'
    cache: false
  - data: github
    json: 'https://api.github.com/orgs/delphix/repos'
    cache: false

featured:
  - name: "Continuous Integration"
    description: "Tools for integrating Delphix into your CI/CD Pipeline"
    repos: ["delphix-plugin"]
  - name: "Automation"
    description: "Tools to help integrate Delphix into your automation toolchain"
    repos: [ "ansible-target-host", "chef", "delphixpy-examples", "puppet"]
  - name: "Management"
    description: "Tools for managing Delphix deployments."
    repos: [ "dxtoolkit", "dxanalyze", "infra-readiness" ]
  - name: "Virtualization"
    description: "Tools to help virtualize data and operate VDBs."
    repos: [ "dxhooks" ]
  - name: "Masking"
    description: "Tools to help mask data and operate masking deployments."
    repos: [ "masking-initializer" ]
  - name: "Forks"
    description: "Forks of external projects where Delphix is a primary contributor."
    repos: [ "zfs", "spl", "delphix-os" ]
