repository: delphix/delphix.github.io
url: https://delphix.github.io/
plugins_dir: ./_plugins

jekyll_xml:
  - data: jenkins
    source: 'https://api.github.com/repos/jenkinsci/delphix-plugin'
    json: true
    cache: true
    auth_user: GITHUB_USER
    auth_pass: GITHUB_TOKEN
  - data: github
    source: 'https://api.github.com/orgs/delphix/repos?page=1&per_page=200'
    json: true
    cache: true
    auth_user: GITHUB_USER
    auth_pass: GITHUB_TOKEN

featured:
  - name: "Continuous Integration"
    description: "Tools for integrating Delphix into your CI/CD Pipeline"
    repos: ["delphix-plugin", "automation-framework"]
  - name: "Automation"
    description: "Tools to help integrate Delphix into your automation toolchain"
    repos: [ "ansible-target-host", "chef", "delphixpy-examples", "puppet"]
  - name: "Management"
    description: "Tools for managing Delphix deployments."
    repos: [ "dxtoolkit", "dxm-toolkit", "dxanalyze", "infra-readiness" ]
  - name: "Virtualization"
    description: "Tools to help virtualize data and operate VDBs."
    repos: [ "dxhooks", "virtualization-sdk" , "couchbase-plugin"]
  - name: "Masking"
    description: "Tools to help mask data and operate masking deployments."
    repos: [ "masking-initializer" ]
  - name: "Forks"
    description: "Forks of external projects where Delphix is a primary contributor."
    repos: [ "zfs", "spl", "delphix-os" ]
