repository: delphix/delphix.github.io

featured:
  - name: "Automation"
    description: "Tools to help integrate Delphix into your automation toolchain"
    repos: [ "ansible-target-host", "delphixpy-examples" ]
  - name: "Management"
    description: "Tools for managing Delphix deployments."
    repos: [ "dxtoolkit", "dxanalyze", "infra-readiness" ]
  - name: "Virtualization"
    description: "Tools to help virtualize data and operate VDBs."
    repos: [ "dxhooks" ]
  - name: "Masking"
    description: "Tools to help mask data and operate masking deployments."
    repos: [ "masking-initializer" ]
  - name: "Forks" 
    description: "Forks of external projects where Delphix is a primary contributor."
    repos: [ "zfs", "spl", "delphix-os" ]
