# .github/workflows/repo-list-update.yaml
name: Update

on:
  [workflow_dispatch]
  
  schedule:
    - cron: '16 30 * * *'

jobs:
  preview:
    name: Update repo list
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - run: bundle install

      - run: JEKYLL_ENV=production bundle exec jekyll build --destination site

      - name: Update repo list
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: master
          FOLDER: ./site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
